- name: Create configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ dirs }}"

- name: Create symlinks from dotfiles repository
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    state: link
  with_items: "{{ links }}"
