# Install workstation software
- hosts: workstation
  become: yes
  roles:
    - install_base-antergos
    - install_i3-antergos
    - install_workstation-antergos

# Configure workstation software
- hosts: workstation
  become: no
  roles:
    - config_base
    - config_i3
    - config_vscode
