---
- hosts: workstation
  become: yes
  roles:
    - common
    - graphics_drivers
    - workstation_config
    - golang
    - java
    - nodejs
    - google_chrome
    - vim
    - tmux
#    - vscode
    - atom
    - intellij-idea
    - goland
    - powerline-go
    - spotify
    - slack
    - dropbox
    - keepassx
    - other
