# Install workstation software
- hosts: workstation
  become: yes
  roles:
    #- google-chrome
    #- vim
    #- spotify
    #- dropbox
    #- keepassx
    #- nvidia-driver
    #- nodejs
    #- golang
    #- java
    #- vscode
    #- docker
    #- zsh
    #- atom
    #- postman
    #- slack
    #- mailspring
    #- intellij
    #- goland
    #- discord
