# Installing Jetbrains Intellij Idea Ultimate Edition using Snap
- name: checking if Intellij Idea Ultimate is installed
  become: false
  shell: type "intellij-idea-ultimate"
  register: result
  changed_when: no
  ignore_errors: true

- name: intalling IntelliJ Idea Ulimate
  command: snap install --classic intellij-idea-ultimate
  when: result|failed