# Installing Mailspring mail client
- name: checking mailspring installed
  become: false
  shell: type "mailspring"
  register: result
  changed_when: no
  ignore_errors: true

- name: installing
  command: snap install mailspring
  when: result|failed
