# Install NodeJS 10.x

- name: checking if NodeJS is installed
  command: node -v
  register: result
  changed_when: no
  ignore_errors: true

- name: downloading NodeJS setup script
  get_url:
    url: https://deb.nodesource.com/setup_10.x
    force: yes
    dest: /tmp/
    mode: 0755
  when: result is failed

- name: running NodeJS setup script
  command: /tmp/setup_9.x
  args:
    chdir: /tmp/
  when: result is failed

- name: removing NodeJS setup script
  file:
    path: /tmp/setup_9.x
    state: absent
  when: result is failed

- name: installing NodeJS
  apt:
    name: nodejs
    update_cache: yes
  when: result is failed