# Installing Visual Studio Code using snap
- name: checking if Visual Studio Code is installed
  become: false
  command: vscode -v
  register: result
  changed_when: no
  ignore_errors: true

- name: installing Visual Studio Code
  command: snap install --classic vscode
  when: result is failed

