extensions:
  - austin.code-gnu-global
  - chenxsan.vscode-standardjs
  - christian-kohler.npm-intellisense
  - chrmarti.regex
  - eamodio.gitlens
  - Equinusocio.vsc-material-theme
  - felixfbecker.php-intellisense
  - gerane.Theme-FlatlandMonokai
  - HookyQR.beautify
  - ikappas.phpcs
  - Jarga.apib
  - jpogran.puppet-vscode
  - maty.vscode-mocha-sidebar
  - ms-vscode.cpptools
  - PeterJausovec.vscode-docker
  - PKief.material-icon-theme
  - samrapdev.outrun
  - shardulm94.trailing-spaces
  - vscodevim.vim
  - wayou.vscode-todo-highlight
  - ms-vscode.Go
  - DavidAnson.vscode-markdownlint
