# Installing Visual Studio Code
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: arch.yml
  when: ansible_distribution == "Archlinux"

# Install extensions
- name: listing installed extensions
  become: no
  command: code --list-extensions
  changed_when: no
  register: installed_ext

- name: installing missing extensions
  become: no
  command: code --install-extension {{ item }}
  when: installed_ext.stdout is not search(item)
  with_items: "{{ extensions }}"

# Apply settings
- name: applying settings.json
  become: no
  file:
    src: "{{ dotfiles }}/vscode.json"
    dest: "{{ home }}/.config/Code/User/settings.json"
    follow: false
    force: yes
    state: link
