# Installing Visual Studio Code using snap
- name: checking vscode installed
  become: false
  command: vscode -v
  register: result
  changed_when: no
  ignore_errors: true

- name: run snap install for vscode
  command: snap install --classic vscode
  when: result|failed

- name: installing extensions
  become: no
  command: code --install-extension {{ item }}
  with_items: "{{ extensions }}"