# Installing Visual Studio Code using snap

- name: checking vscode installed
  become: false
  command: vscode --user-data-dir /tmp -v
  register: vscode_installed
  changed_when: false

- name: run snap install for vscode
  command: snap install --classic vscode
  when: vscode_installed == false