# Installing NodeJS - Ubuntu
- name: checking if installed
  command: node -v
  register: result
  changed_when: no
  ignore_errors: true

- name: downloading setup script
  get_url:
    url: https://deb.nodesource.com/setup_{{ version }}
    force: yes
    dest: /tmp/node_setup
    mode: 0755
  when: result is failed

- name: running setup script
  command: /tmp/node_setup
  args:
    chdir: /tmp/
  when: result is failed

- name: removing setup script
  file:
    path: /tmp/node_setup
    state: absent
  when: result is failed

- name: installing
  apt:
    name: nodejs
    update_cache: yes
  when: result is failed