- name: Installing extensions
  command: code --install-extension {{ item }}
  with_items: "{{ extensions }}"

- name: Applying settings.json
  file:
    src: ~/dotfiles/vscode/settings.json
    dest: ~/.config/Code/User/settings.json
    force: yes
    state: link