- name: Copying .xinitrc configuration file
  copy:
    src: xorg/.xinitrc
    dest: "/home/{{ ansible_user }}/.xinitrc"
    owner: "{{ ansible_user }}"

- name: Copying .Xresources configuration file
  copy:
    src: xorg/.Xresources
    dest: "/home/{{ ansible_user }}/.Xresources"
    owner: "{{ ansible_user }}"

- name: Create i3 directory
  file:
    path: "/home/{{ ansible_user }}/.config/i3"
    state: directory
    owner: "{{ ansible_user }}"

- name: Copying i3 configuration file
  template:
    src: i3/config.j2
    dest: "/home/{{ ansible_user }}/.config/i3/config"
    owner: "{{ ansible_user }}"

- name: Copying variety set_wallpaper script
  copy:
    src: variety/set_wallpaper
    dest: "/home/{{ ansible_user }}/.config/variety/scripts/set_wallpaper"
    owner: "{{ ansible_user }}"

- name: Copying .gtkrc-2.0 config file
  template:
    src: gtk/.gtkrc-2.0.j2
    dest: "/home/{{ ansible_user }}/.gtkrc-2.0"
    owner: "{{ ansible_user }}"

- name: Copying gtk-3.0 config file
  template:
    src: gtk/settings.ini.j2
    dest: "/home/{{ ansible_user }}/.config/gtk-3.0/settings.ini"
    owner: "{{ ansible_user }}"
