- name: Copying .bashrc
  copy:
    src: .bashrc
    dest: "/home/{{ ansible_user }}/.bashrc"
    owner: "{{ ansible_user }}"

- name: Copying .vimrc
  copy:
    src: .vimrc
    dest: "/home/{{ ansible_user }}/.vimrc"
    owner: "{{ ansible_user }}"

- name: Copying .nanorc
  copy:
    src: .nanorc
    dest: "/home/{{ ansible_user }}/.nanorc"
    owner: "{{ ansible_user }}"

- name: Copying .tmux.conf
  copy:
    src: .tmux.conf
    dest: "/home/{{ ansible_user }}/.tmux.conf"
    owner: "{{ ansible_user }}"

- name: Copying .xinitrc configuration file
  copy:
    src: xorg/.xinitrc
    dest: "/home/{{ ansible_user }}/.xinitrc"
    owner: "{{ ansible_user }}"

- name: Copying .Xresources configuration file
  copy:
    src: xorg/.Xresources
    dest: "/home/{{ ansible_user }}/.Xresources"
    owner: "{{ ansible_user }}"
  register: xresources

- name: Copying i3 configuration file
  copy:
    src: i3/config
    dest: "/home/{{ ansible_user }}/.config/i3/config"
    owner: "{{ ansible_user }}"

- name: Copying .gtkrc-2.0 config file
  copy:
    src: gtk/.gtkrc-2.0
    dest: "/home/{{ ansible_user }}/.gtkrc-2.0"
    owner: "{{ ansible_user }}"

- name: Copying gtk-3.0 config file
  copy:
    src: gtk/settings.ini
    dest: "/home/{{ ansible_user }}/.config/gtk-3.0/settings.ini"
    owner: "{{ ansible_user }}"

- name: Copying .polybar config
  copy:
    src: polybar/config
    dest: "/home/{{ ansible_user }}/.config/polybar/config"
    owner: "{{ ansible_user }}"

- name: Copying polybar launch script
  copy:
    src: polybar/polybar.sh
    dest: "/home/{{ ansible_user }}/.config/polybar/polybar.sh"
    owner: "{{ ansible_user }}"
    mode: 0744

- name: Copying wallpaper
  copy:
    src: wallpaper.png
    dest: "/home/{{ ansible_user }}/Pictures/wallpaper.png"
    owner: "{{ ansible_user }}"

- name: Copying dunstrc
  copy:
    src: dunst/dunstrc
    dest: "/home/{{ ansible_user }}/.config/dunst/dunstrc"
    owner: "{{ ansible_user }}"
