# Creating all needed folders
- name: Creating folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
  with_items: "{{ folders }}"

# Installing xorg and surrounding packages
- name: Installing packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

# Installing nvidia installer and running the program
- include: nvidia_driver.yml

# Installing AUR packages
- name: Installing AUR packages
  aur:
    name: "{{ item }}"
    dir: /opt/aur
    user: "{{ ansible_user }}"
  with_items: "{{ aur }}"

# Copying dotfiles to target system
- include: config_files.yml
