# Installing ZSH - Ubuntu
- name: installing zsh
  apt:
    name: zsh

- name: installing powerline fonts
  apt:
    name: fonts-powerline

- name: downloading oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/oh-my-zsh-installer.sh

- name: installing oh-my-zsh
  shell: /tmp/oh-my-zsh-installer.sh

- name: get current default shell
  shell: echo $SHELL
  register: shell

- name: set zsh as default
  shell: chsh -s $(which zsh)
  when: shell == "/usr/bin/zsh"
