# Installing xorg and surrounding packages
- name: Installing packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

# Installing nvidia installer and running the program
- name: Installing nvidia propriatary drivers installer
  pacman:
    name: nvidia-installer
    state: present
  register: installer

- name: Run nvidia installer
  shell: nvidia-installer
  when: installer.changed

# Installing AUR packages
- name: Installing AUR packages
  aur:
    name: "{{ item }}"
    dir: /opt/aur
    user: "{{ ansible_user }}"
  with_items: "{{ aur }}"
