# Installing Atom - Ubuntu
- name: checking if installed
  become: false
  shell: type "caprine"
  register: result
  changed_when: no
  ignore_errors: true

- name: installing
  command: snap install caprine
  when: result is failed
