# Installing VIM
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: creating symlink .vimrc
  become: no
  file:
    src: "{{ dotfile }}"
    dest: ~/.vimrc
    state: link

- name: installing vim plugins
  shell: vim +PlugInstall +qall
