# Installing VIM
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: arch.yml
  when: ansible_distribution == "Archlinux"

- name: test
  become: no
  debug:
    msg: "{{ ansible_distribution }}"

- name: creating symlink .vimrc
  become: no
  file:
    src: "{{ dotfiles }}/vimrc"
    dest: "{{ home }}/.vimrc"
    state: link

