# Installing VIM
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: creating symlink .vimrc
  become: no
  file:
    src: "{{ dotfile }}"
    dest: ~/.vimrc
    state: link


- name: creating vim autoload path
  file: 
    path:  ~/.vim/autoload
    state: directory

- name: installing vim-plug
  become: no
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: installing vim plugins
  shell: vim +PlugInstall +qall
