# Installing VIM - Ubuntu
- name: installing
  apt:
    name: vim
    state: present

- name: installing vim-plug
  become: no
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
